In [1]:
import pandas as pd

In [2]:
df = pd.read_json('../data/raw/projects_freelancer.jsonl', lines=True)

In [3]:
df.head()

,title,description,budget_min,budget_max,currency,budget_type,skills,project_url,category,subcategory,platform
0,All-in-One Travel Booking Platform,The platform will include:\n• Hotel booking\n•...,750,1250.0,INR,hourly,"[.NET, Website Design, Inventory Management, H...",https://www.freelancer.com/projects/dot-net/al...,"Websites, IT & Software",.NET,Freelancer
1,Power Automate Consultant for Business Automat...,About the role\nWe're a multi-location automot...,750,1500.0,USD,fixed_price,"[Power Automate, Microsoft 365, Data Managemen...",https://www.freelancer.com/projects/power-auto...,"Websites, IT & Software",Power Automate,Freelancer
2,Employee Hours/ Holiday/ Sickness tracker,I'm looking for a Windows desktop application ...,20,250.0,GBP,fixed_price,"[Desktop Application, Alerting, Software Devel...",https://www.freelancer.com/projects/desktop-ap...,"Websites, IT & Software",Desktop Application,Freelancer
3,Custom Image Puzzle Generator,I need a standalone Windows application that t...,10,100.0,USD,fixed_price,"[SVG, Software Development, Desktop Applicatio...",https://www.freelancer.com/projects/svg/custom...,"Websites, IT & Software",SVG,Freelancer
4,C# Real-Time Automation App,I need a Windows desktop application written i...,1500,12500.0,INR,fixed_price,"[REST API, JSON, Visual Studio, Software Devel...",https://www.freelancer.com/projects/rest-api/r...,"Websites, IT & Software",REST API,Freelancer

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4372 entries, 0 to 4371
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        4372 non-null   str
 1   description  4372 non-null   str
 2   budget_min   4372 non-null   int64
 3   budget_max   4278 non-null   float64
 4   currency     4372 non-null   str
 5   budget_type  4372 non-null   str
 6   skills       4372 non-null   object
 7   project_url  4372 non-null   str
 8   category     4372 non-null   str
 9   subcategory  4372 non-null   str
 10  platform     4372 non-null   str
dtypes: float64(1), int64(1), object(1), str(8)
memory usage: 375.8+ KB

In [5]:
df.isna().sum()

title           0
description     0
budget_min      0
budget_max     94
currency        0
budget_type     0
skills          0
project_url     0
category        0
subcategory     0
platform        0
dtype: int64

In [6]:
df.loc[df['budget_max'].isna()]

,title,description,budget_min,budget_max,currency,budget_type,skills,project_url,category,subcategory,platform
35,Email Marketing Copywriter Needed,I’m planning a fresh sequence of marketing ema...,50,NaN,USD,hourly,"[A/B Testing, Article Writing, Content Writing...",https://www.freelancer.com/projects/ab-testing...,"Websites, IT & Software",A/B Testing,Freelancer
113,Corporate Slide Deck Revamp with Animation,I'm seeking a skilled designer to enhance my s...,36,NaN,GBP,hourly,"[Adobe Creative Cloud, Adobe Animate, Visual D...",https://www.freelancer.com/projects/adobe-crea...,"Websites, IT & Software",Adobe Creative Cloud,Freelancer
806,Long-Term Technical Partner Wanted (EU/US),Looking for a Long-Term Technical Partner (Eur...,50,NaN,USD,hourly,"[Software Development, Cloud Computing, Backen...",https://www.freelancer.com/projects/software-d...,"Websites, IT & Software",Software Development,Freelancer
812,Software Product Manager & Analyst,I’m bringing a new technology-driven software ...,2500,NaN,INR,hourly,"[Product Management, Agile Development, Softwa...",https://www.freelancer.com/projects/product-ma...,"Websites, IT & Software",Product Management,Freelancer
817,Custom Dynamics 365 CRM Builder,I am rolling out Microsoft Dynamics 365 to cov...,50,NaN,USD,hourly,"[API, CRM, Microsoft, Data Integration, HTML, ...",https://www.freelancer.com/projects/api/custom...,"Websites, IT & Software",API,Freelancer
...,...,...,...,...,...,...,...,...,...,...,...
4240,Audio Transcriptionist Wanted | Arabic - Mixed...,We are looking for a freelance audio transcrip...,71,NaN,USD,hourly,"[Arabic Translator, AI (Artificial Intelligenc...",https://www.freelancer.com/projects/arabic-tra...,Artificial Intelligence,Arabic Translator,Freelancer
4241,Audio Transcriptionist Wanted | Arabic - Saudi...,We are looking for a freelance audio transcrip...,78,NaN,USD,hourly,"[Arabic Translator, AI (Artificial Intelligenc...",https://www.freelancer.com/projects/arabic-tra...,Artificial Intelligence,Arabic Translator,Freelancer
4242,Audio Transcriptionist Wanted | Arabic - Egypt...,We are looking for a freelance audio transcrip...,43,NaN,USD,hourly,"[Arabic Translator, AI (Artificial Intelligenc...",https://www.freelancer.com/projects/arabic-tra...,Artificial Intelligence,Arabic Translator,Freelancer
4243,Audio Transcriptionist Wanted | Spanish - Spai...,We are looking for a freelance audio transcrip...,78,NaN,USD,hourly,"[Spanish Translator, AI (Artificial Intelligen...",https://www.freelancer.com/projects/spanish-tr...,Artificial Intelligence,Spanish Translator,Freelancer
4244,Audio Transcriptionist Wanted | Portuguese - B...,We are looking for a freelance audio transcrip...,32,NaN,USD,hourly,"[Portuguese Translator, AI (Artificial Intelli...",https://www.freelancer.com/projects/portuguese...,Artificial Intelligence,Portuguese Translator,Freelancer

In [7]:
df['currency'].value_counts()

currency
USD    2285
INR    1682
EUR     241
GBP     164
Name: count, dtype: int64

In [8]:
df['budget_type'].value_counts()

budget_type
fixed_price    3402
hourly          970
Name: count, dtype: int64

In [9]:
df['category'].value_counts()

category
Websites, IT & Software    4222
Artificial Intelligence     150
Name: count, dtype: int64

In [10]:
df['project_url'].value_counts()

project_url
https://www.freelancer.com/projects/dot-net/all-one-travel-booking-platform                        1
https://www.freelancer.com/projects/power-automate/power-automate-consultant-for-business          1
https://www.freelancer.com/projects/desktop-application/employee-hours-holiday-sickness-tracker    1
https://www.freelancer.com/projects/svg/custom-image-puzzle-generator                              1
https://www.freelancer.com/projects/rest-api/real-time-automation-app                              1
                                                                                                  ..
https://www.freelancer.com/projects/machine-translation/hebrew-translation-quality-reviewer        1
https://www.freelancer.com/projects/copywriting/logo-copywriting-poster                            1
https://www.freelancer.com/projects/object-detection/outdoor-ultrasonic-vehicle-detection          1
https://www.freelancer.com/projects/voice-over/speech-recording-task                               1
https://www.freelancer.com/projects/email-handling/virtual-assistant-needed-40553154               1
Name: count, Length: 4372, dtype: int64

In [11]:
print("Rows:", df.shape[0])
print("Unique URLs:", df['project_url'].nunique())
print("Duplicate URLs:", df['project_url'].duplicated().sum())

print(f"\n{df['budget_type'].value_counts()}")
print(f"\n{df['currency'].value_counts()}")
print(f"\n{df['category'].value_counts()}")
print(f"\n{df['subcategory'].value_counts()}")

Rows: 4372
Unique URLs: 4372
Duplicate URLs: 0

budget_type
fixed_price    3402
hourly          970
Name: count, dtype: int64

currency
USD    2285
INR    1682
EUR     241
GBP     164
Name: count, dtype: int64

category
Websites, IT & Software    4222
Artificial Intelligence     150
Name: count, dtype: int64

subcategory
Web Development                200
Adobe Premiere Pro             155
Adobe Illustrator              152
Web Design                     122
Social Media Management         81
                              ...
Music Production                 1
Comedy Writing                   1
Architectural Visualization      1
Machine Translation              1
Email Handling                   1
Name: count, Length: 671, dtype: int64

In [12]:
df['skills'].apply(len).describe()

count    4372.000000
mean        8.136322
std         1.603356
min         2.000000
25%         8.000000
50%         8.000000
75%        10.000000
max        12.000000
Name: skills, dtype: float64

In [13]:
df['subcategory'].value_counts()

subcategory
Web Development                200
Adobe Premiere Pro             155
Adobe Illustrator              152
Web Design                     122
Social Media Management         81
                              ...
Music Production                 1
Comedy Writing                   1
Architectural Visualization      1
Machine Translation              1
Email Handling                   1
Name: count, Length: 671, dtype: int64