In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../data/raw/projects_merged.jsonl", lines=True)

In [3]:
df.head()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
0,Implementador de Crm/Whatsapp Api con Automati...,Se busca un implementador freelance con experi...,250.0,500.0,fixed_price,"[CRM, API, Facebook, Scripts & Utilities, Data...",Programación y Tecnología,Tiendas Online (e-commerce),https://www.workana.com/job/implementador-de-c...,Workana,USD
1,"Automatización de Facturas con Ocr, Zapier e I...",Se busca un programador experto para diseñar e...,500.0,1000.0,fixed_price,"[SQL, Database, ERP, API, System Analysis, Mod...",Programación y Tecnología,Programación Web,https://www.workana.com/job/automatizacion-de-...,Workana,USD
2,Desarrollador Node.js / Sqlite para Proyecto C...,Buscamos un programador backend con perfil Jun...,100.0,250.0,fixed_price,"[Node.js, Express.js, SQL, Database, API]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-node...,Workana,USD
3,Desarrollador Wordpress + Elementor Pro para L...,Busco desarrollador con experiencia comprobabl...,100.0,250.0,fixed_price,"[WordPress, HTML, CSS, Responsive Web Design]",Programación y Tecnología,Programación Web,https://www.workana.com/job/desarrollador-word...,Workana,USD
4,Especialista Itil para Diseño e Implementación...,Actualmente me desempeño como Jefe de Servicio...,NaN,15.0,hourly,"[Informática, Technical Support, System Analys...",Programación y Tecnología,Otros,https://www.workana.com/job/especialista-itil-...,Workana,USD

In [4]:
df.tail()

,title,description,budget_min,budget_max,budget_type,skills,category,subcategory,project_url,platform,currency
4718,Hebrew Translation Quality Reviewer,I have a year-long project that needs a sharp ...,8.0,15.0,hourly,"[Machine Translation, Language Tutoring, Editi...",Artificial Intelligence,Machine Translation,https://www.freelancer.com/projects/machine-tr...,Freelancer,USD
4719,"Logo, Copywriting & AI Poster",Saya mencari seorang kreatif yang bisa mengeks...,8.0,15.0,hourly,"[Copywriting, Adobe Illustrator, Adobe Photosh...",Artificial Intelligence,Copywriting,https://www.freelancer.com/projects/copywritin...,Freelancer,USD
4720,Outdoor Ultrasonic Vehicle Detection,I need assistance in developing electronic for...,25.0,50.0,hourly,"[Object Detection, Embedded Systems, Electroni...",Artificial Intelligence,Object Detection,https://www.freelancer.com/projects/object-det...,Freelancer,USD
4721,Speech Recording Task,I need native-sounding adults (25 years or old...,100.0,400.0,hourly,"[Voice Over, Speech Synthesis, Voice Acting, A...",Artificial Intelligence,Voice Over,https://www.freelancer.com/projects/voice-over...,Freelancer,INR
4722,10 Virtual Assistants Needed,I have a heavy workload managing emails and ch...,250.0,750.0,fixed_price,"[Email Handling, Chat Operation, Virtual Assis...",Artificial Intelligence,Email Handling,https://www.freelancer.com/projects/email-hand...,Freelancer,USD

## 1. Dataset Overview

In [5]:
print(f"Total projects: {df.shape[0]}")

Total projects: 4723

In [6]:
print(f"Workana projects: {df.loc[df['platform'] == 'Workana'].shape[0]}")

Workana projects: 351

In [7]:
print(f"Freelancer projects: {df.loc[df['platform'] == 'Freelancer'].shape[0]}")

Freelancer projects: 4372

In [8]:
print(f"Percentage of Workana projects: {df.loc[df['platform'] == 'Workana'].shape[0] / df.shape[0] * 100:.2f}%")
print(f"Percentage of Freelancer projects: {df.loc[df['platform'] == 'Freelancer'].shape[0] / df.shape[0] * 100:.2f}%")

Percentage of Workana projects: 7.43%
Percentage of Freelancer projects: 92.57%