## 1. Dataset Overview

In [1]:
import sys
from pathlib import Path

project_root = Path().resolve().parent
sys.path.append(str(project_root))

In [2]:
from database.connection import engine
from sqlalchemy import text
import pandas as pd

query = text("SELECT * FROM projects_raw")
df = pd.read_sql_query(query, engine)

In [3]:
filas, columnas = df.shape
print(f"Columnas: {columnas} --- Filas: {filas}")

Columnas: 13 --- Filas: 4722

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           4722 non-null   int64
 1   title        4722 non-null   str
 2   description  4722 non-null   str
 3   budget_min   4696 non-null   float64
 4   budget_max   4589 non-null   float64
 5   budget_type  4722 non-null   str
 6   skills       4722 non-null   object
 7   category     4722 non-null   str
 8   subcategory  4722 non-null   str
 9   project_url  4722 non-null   str
 10  platform     4722 non-null   str
 11  currency     4722 non-null   str
 12  created_at   4722 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(8)
memory usage: 479.7+ KB

In [5]:
type(df["skills"].iloc[0])

list

In [6]:
print(f"NULLS 'budget_min': {((df['budget_min'].isna().sum() / df.shape[0]) * 100):.2f}%")
print(f"NULLS 'budget_max': {((df['budget_max'].isna().sum() / df.shape[0]) * 100):.2f}%")

NULLS 'budget_min': 0.55%
NULLS 'budget_max': 2.82%

In [13]:
print(df.loc[df['platform'] == 'Workana'].shape[0])
print(df.loc[df['platform'] == 'Freelancer'].shape[0])

350
4372

In [7]:
df.describe()

                id    budget_min    budget_max                  created_at
count  4722.000000  4.696000e+03  4.589000e+03                        4722
mean   2361.500000  5.334954e+03  1.309124e+04  2026-07-25 07:37:02.107949
min       1.000000  2.000000e+00  4.000000e+00  2026-07-25 07:37:02.107950
25%    1181.250000  3.000000e+01  1.600000e+02  2026-07-25 07:37:02.107950
50%    2361.500000  2.500000e+02  7.500000e+02  2026-07-25 07:37:02.107950
75%    3541.750000  1.500000e+03  3.000000e+03  2026-07-25 07:37:02.107950
max    4722.000000  5.000000e+06  1.000000e+07  2026-07-25 07:37:02.107950
std    1363.268315  7.749513e+04  1.596335e+05                         NaN

In [ ]:
((df.loc[df['budget_max'] > 3000].shape[0]) / df.shape[0] * 100)

23.33756882676832

In [20]:
df.loc[df['budget_max'] > 100000].shape[0]

60

In [21]:
df['currency'].value_counts()

currency
USD    2635
INR    1682
EUR     241
GBP     164
Name: count, dtype: int64

In [22]:
df.loc[df['budget_min'] > df['budget_max']]

Empty DataFrame
Columns: [id, title, description, budget_min, budget_max, budget_type, skills, category, subcategory, project_url, platform, currency, created_at]
Index: []